[package]
name = "pattern_engine"
version = "0.1.0"
authors = ["Sam Blazes <sblazes@caltech.edu>"]

[dependencies]
bson = "0.11"
bitboard = {path = "../bitboard"}
heuristic = {path = "../heuristic"}
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"