[package]
name = "pattern_engine"
version = "0.1.0"
authors = ["Sam Blazes <sblazes@caltech.edu>"]

[dependencies]
bson = "0.8.0"
bitboard = {path = "../bitboard"}
rand = "0.3"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"

[dev-dependencies]
time = "0.1.37"