[package]
name = "search"
version = "0.1.0"
authors = ["Sam Blazes <sblazes@caltech.edu>"]

[dependencies]
bitboard = {path = "../bitboard"}
heuristic = {path = "../heuristic"}
rand = "0.3"
rayon = "0.9.0"

[dev-dependencies]